"""Increments jarvis/build_info.py's BUILD_NUMBER -- but ONLY when the
actual source under jarvis-cli/jarvis/ has changed since the last bump.
Re-running script.bat with no source edits leaves BUILD_NUMBER (and
BUILT_AT) exactly as they were; it does NOT bump just because a build was
attempted. See hash_source.py for the hashing this decision is based on.

WHY A COUNTER AT ALL, GIVEN THE HASH ALREADY ANSWERS "DID SOURCE CHANGE":
the hash is precise but not human-skimmable across builds ("build 7" vs
"build 8" is a much faster glance than comparing two 12-char hex
strings). BUILD_NUMBER and SOURCE_HASH are stored together in
build_info.py and both are shown by `jarvis version` -- the number for
quick comparison, the hash for an exact one (and for verify_exe.py, which
only ever compares hashes, never numbers).

Run by script.bat, from jarvis-cli/, BEFORE `pip install .` (so whatever
this writes is what gets baked into the wheel installed this run):

    python build_tools\\bump_build_version.py

Prints "<build_number> <source_hash>" to stdout on success (nothing
else), whether or not a bump actually happened -- script.bat always
wants both current values to log, regardless. A human-readable note
about whether a bump occurred goes to stderr instead, so it doesn't
break the stdout contract.
"""

import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from hash_source import hash_source_tree, short_hash  # noqa: E402

BUILD_INFO_PATH = Path(__file__).resolve().parent.parent / "jarvis" / "build_info.py"

_NUMBER_RE = re.compile(r"(?m)^BUILD_NUMBER\s*=\s*(\d+)\s*$")
_HASH_RE = re.compile(r'(?m)^SOURCE_HASH\s*=\s*"([0-9a-f]*)"\s*$')

TEMPLATE = '''"""Auto-generated build metadata -- DO NOT EDIT BY HAND.

Regenerated by build_tools/bump_build_version.py every time script.bat
builds -- but BUILD_NUMBER/SOURCE_HASH/BUILT_AT only actually CHANGE when
the source under jarvis-cli/jarvis/ has changed since the last bump (see
that file's docstring). Re-running a build with no source edits leaves
this file byte-for-byte untouched.

SOURCE_HASH is the real check: it's what a currently-installed exe was
actually built from, recomputable at any time from source on disk via
build_tools/hash_source.py, and what build_tools/verify_exe.py compares
against whatever `jarvis` on PATH reports. BUILD_NUMBER is just a
human-skimmable counter alongside it -- never trust the number alone for
"is this exe current", trust SOURCE_HASH matching.

Safe to commit. Safe to delete -- bump_build_version.py recreates it from
scratch (starting at build 1) if it's missing.
"""

BUILD_NUMBER = {number}
SOURCE_HASH = "{source_hash}"
BUILT_AT = "{built_at}"


def version_string():
    """'jarvis-cli <pkg-version> build <N> [src <hash>] (<built-at>)' --
    <pkg-version> comes from the installed package's own metadata
    (pyproject.toml's [project].version), not duplicated here, so it can
    never drift out of sync with the real thing. Falls back gracefully
    if the package isn't installed the normal way (e.g. running straight
    from source). The "[src ...]" segment is what verify_exe.py greps
    out of `jarvis version`'s output -- keep that exact "[src <hex>]"
    shape if you ever touch this format."""
    try:
        from importlib.metadata import version as _pkg_version
        pkg_version = _pkg_version("jarvis-cli")
    except Exception:
        pkg_version = "unknown"

    hash_bit = f" [src {{SOURCE_HASH[:12]}}]" if SOURCE_HASH else ""
    built = f" ({{BUILT_AT}})" if BUILT_AT else ""
    return f"jarvis-cli {{pkg_version}} build {{BUILD_NUMBER}}{{hash_bit}}{{built}}"
'''


def bump(path=BUILD_INFO_PATH):
    """Returns (build_number, source_hash, bumped_bool). Writes the file
    only when bumped_bool is True."""
    current_number = 0
    previous_hash = ""
    if path.exists():
        text = path.read_text(encoding="utf-8")
        match = _NUMBER_RE.search(text)
        if match:
            current_number = int(match.group(1))
        hash_match = _HASH_RE.search(text)
        if hash_match:
            previous_hash = hash_match.group(1)

    new_hash = hash_source_tree()

    if current_number > 0 and new_hash == previous_hash:
        # Source is byte-for-byte identical to the last bump -- do NOT
        # increment. This is the whole point: the counter tracks "has
        # the source changed", not "did script.bat run again".
        return current_number, new_hash, False

    new_number = current_number + 1
    built_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    path.write_text(
        TEMPLATE.format(number=new_number, source_hash=new_hash, built_at=built_at),
        encoding="utf-8",
    )
    return new_number, new_hash, True


def main():
    try:
        number, src_hash, bumped = bump()
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    # stdout contract: "<number> <hash>", nothing else -- script.bat
    # parses this with `tokens=1,2`.
    sys.stdout.write(f"{number} {src_hash}")

    if bumped:
        print(
            f"[build] Source changed -> build {number} (hash {short_hash(src_hash)})",
            file=sys.stderr,
        )
    else:
        print(
            f"[build] Source unchanged since build {number} (hash {short_hash(src_hash)}) "
            "-- number not bumped",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
