"""Auto-generated build metadata -- DO NOT EDIT BY HAND.

Regenerated by build_tools/bump_build_version.py every time script.bat
builds -- but BUILD_NUMBER/SOURCE_HASH/BUILT_AT only actually CHANGE when
the source under jarvis-cli/jarvis/ has changed since the last bump (see
that file's docstring). Re-running a build with no source edits leaves
this file byte-for-byte untouched.

SOURCE_HASH is the real check: it's what a currently-installed exe was
actually built from, recomputable at any time from source on disk via
build_tools/hash_source.py, and what build_tools/verify_exe.py compares
against whatever `jarvis` on PATH reports. BUILD_NUMBER is just a
human-skimmable counter alongside it -- never trust the number alone for
"is this exe current", trust SOURCE_HASH matching.

Safe to commit. Safe to delete -- bump_build_version.py recreates it from
scratch (starting at build 1) if it's missing.
"""

BUILD_NUMBER = 31
SOURCE_HASH = "48406d05fef8b503080aa6770743b2d7612788771f217ab8a26dbdbc8c144bdd"
BUILT_AT = "2026-09-25 12:13:05"


def version_string():
    """'jarvis-cli <pkg-version> build <N> [src <hash>] (<built-at>)' --
    <pkg-version> comes from the installed package's own metadata
    (pyproject.toml's [project].version), not duplicated here, so it can
    never drift out of sync with the real thing. Falls back gracefully
    if the package isn't installed the normal way (e.g. running straight
    from source). The "[src ...]" segment is what verify_exe.py greps
    out of `jarvis version`'s output -- keep that exact "[src <hex>]"
    shape if you ever touch this format."""
    try:
        from importlib.metadata import version as _pkg_version
        pkg_version = _pkg_version("jarvis-cli")
    except Exception:
        pkg_version = "unknown"

    hash_bit = f" [src {SOURCE_HASH[:12]}]" if SOURCE_HASH else ""
    built = f" ({BUILT_AT})" if BUILT_AT else ""
    return f"jarvis-cli {pkg_version} build {BUILD_NUMBER}{hash_bit}{built}"
